### ISSUE TITLE
Add test for transformKeys and response processing

### ISSUE THREAD

**Issue by phieronymus** [univapay/univapay-node#18]
- Test with object
- Test with array
- Test with string

**Comment by laxa88** [comment]
We have methods scattered across the project. While we're at it, perhaps it's good to consider adding unit tests for them if possible?

**Comment by phieronymus** [comment]
Yes. This ticket is for the ones related to the API response processing. For other functions we can open other tickets 🙂 The subject is already pretty big.

**Comment by phieronymus** [comment]
Test have been added in `object.specs.ts` after a refactoring. Closing the ticket.
