### ISSUE TITLE
Support JS consumer without having them to require tslib

### ISSUE THREAD

**Issue by phieronymus** [univapay/univapay-node#52]
The `univapay-node-es` does not work without the `tslib` package. The ticket requires to fix the build in order to provide a version that can work out of the box for JS projects.

**Comment by perrin4869** [comment]
hm... the bundler is complaining to me regarding `tslib` here: https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/247805970927/projects/ServicesPullRequestTestProject/build/ServicesPullRequestTestProject%3Aacc2135c-8c1c-45cb-93d8-5a1b6e0c5de8?region=ap-northeast-1
I think it should be a regular dependency of this module?
For example, `@aws/dynamodb-data-mapper` modules are including it: https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/package.json (not sure how much of a role model they are though haha)
But I haven't seen other typescript modules requiring it as a peer dependency, so it's probably best to bundle it...
@phieronymus what do you think?

**Comment by phieronymus** [comment]
If this is solving this issue as a quick fix the package would be far more usable so I agree with the solution.

On the other hand I fail to understand why it is required in the packages that consume it. I did not investigate it much though 🤔 Maybe something somewhat obvious I am missing.
